"""Emulator diagnostics, fail-closed observation capture, and AI contracts."""

from .bluestacks import (
    AdbObservationCapture,
    BlueStacksDiagnostics,
    BlueStacksInstance,
    CapturePlan,
    CapturePayload,
    ExternalCaptureUnavailable,
    discover_bluestacks,
    parse_bluestacks_config,
)
from .env import (
    EnvObservation,
    LegalActionMask,
    MaskStatus,
    ObservationProvenance,
    ObservationSource,
    PublicEvent,
)
from .models import (
    AnnotationSource,
    ArtifactKind,
    BoundingBox,
    CaptureAnnotation,
    CaptureArtifact,
    CaptureManifest,
    ConformanceCheck,
    ConformanceVerdict,
    GroundedField,
    GroundingFrame,
    GroundingSource,
    GroundingStatus,
    GroundingTrace,
    GroundingTraceStatus,
    RedactionRegion,
    RedactionStatus,
)
from .store import CaptureStore
from .validation import (
    GroundingValidationError,
    ValidatedCaptureBinding,
    ValidatedEnvObservation,
    ValidatedGroundingTrace,
    validate_env_observation_against_trace_and_store,
    validate_grounding_trace_against_store,
)

__all__ = [
    "AnnotationSource",
    "AdbObservationCapture",
    "ArtifactKind",
    "BlueStacksDiagnostics",
    "BlueStacksInstance",
    "BoundingBox",
    "CaptureAnnotation",
    "CaptureArtifact",
    "CaptureManifest",
    "CapturePayload",
    "CapturePlan",
    "CaptureStore",
    "ConformanceCheck",
    "ConformanceVerdict",
    "EnvObservation",
    "ExternalCaptureUnavailable",
    "GroundedField",
    "GroundingFrame",
    "GroundingSource",
    "GroundingStatus",
    "GroundingTrace",
    "GroundingTraceStatus",
    "GroundingValidationError",
    "LegalActionMask",
    "MaskStatus",
    "ObservationProvenance",
    "ObservationSource",
    "PublicEvent",
    "RedactionRegion",
    "RedactionStatus",
    "ValidatedCaptureBinding",
    "ValidatedEnvObservation",
    "ValidatedGroundingTrace",
    "discover_bluestacks",
    "parse_bluestacks_config",
    "validate_env_observation_against_trace_and_store",
    "validate_grounding_trace_against_store",
]
