"""Public contracts for the deterministic Champions simulator core."""

from .canonical import canonical_hash, canonical_json, to_canonical_data
from .implementation import (
    class_runtime_sha256,
    class_source_sha256,
    component_state_sha256,
)
from .errors import UnsupportedMechanic
from .ids import (
    AbilityId,
    ItemId,
    MoveId,
    PokemonId,
    PokemonInstanceId,
    RuleSetId,
)
from .model import (
    ActionKind,
    ActionSelection,
    BattleEvent,
    BattleEventKind,
    BattlePhase,
    BattleState,
    DecisionKind,
    DecisionRequest,
    DecisionRequestSet,
    LegalAction,
    MegaEvolutionStatProfile,
    MoveSlotState,
    ObservedMove,
    ObservedPokemon,
    ObservedSide,
    PlayerId,
    PlayerObservation,
    PokemonState,
    SideState,
    StatBlock,
    StatStages,
    TrainingStatBlock,
    TransitionResult,
    make_player_observation,
)
from .replay import (
    BATTLE_STATE_ENCODING,
    REPLAY_SCHEMA_VERSION,
    RNG_ALGORITHM_ID,
    SIMULATOR_VERSION,
    ReplayBundle,
    ReplayInitialState,
    ReplayOutcome,
    ReplayRecord,
    ReplayRedaction,
    ReplayResult,
    ReplayStep,
    ReplayVisibility,
)
from .rng import ExplicitRNG

__all__ = [
    "AbilityId",
    "ActionKind",
    "ActionSelection",
    "BattleEvent",
    "BattleEventKind",
    "BattlePhase",
    "BattleState",
    "DecisionKind",
    "DecisionRequest",
    "DecisionRequestSet",
    "ExplicitRNG",
    "ItemId",
    "LegalAction",
    "MegaEvolutionStatProfile",
    "MoveId",
    "MoveSlotState",
    "ObservedMove",
    "ObservedPokemon",
    "ObservedSide",
    "PlayerId",
    "PlayerObservation",
    "PokemonId",
    "PokemonInstanceId",
    "PokemonState",
    "BATTLE_STATE_ENCODING",
    "REPLAY_SCHEMA_VERSION",
    "RNG_ALGORITHM_ID",
    "SIMULATOR_VERSION",
    "ReplayBundle",
    "ReplayInitialState",
    "ReplayOutcome",
    "ReplayRecord",
    "ReplayRedaction",
    "ReplayResult",
    "ReplayStep",
    "ReplayVisibility",
    "RuleSetId",
    "SideState",
    "StatBlock",
    "StatStages",
    "TrainingStatBlock",
    "TransitionResult",
    "UnsupportedMechanic",
    "canonical_hash",
    "canonical_json",
    "class_runtime_sha256",
    "class_source_sha256",
    "component_state_sha256",
    "make_player_observation",
    "to_canonical_data",
]
